#!/bin/bash
website="https://toonitalia.pro/le-nuove-avventure-di-lupin-iii/" # Modifica questo link e le regex per riutilizzare questo script
website_file="website.html"
website2_file="website2.html"
website3_file="website3.html"
link_file="links.html"

wget --no-verbose $website --output-document=$website_file
grep -Po "https:\/\/streamcrypt.net\/streamz.cc\/\w*" $website_file > $link_file # Regex per trovare i singoli link dei file (pre-download)

rm $website_file

read -p "Number of episode alredy downloaded:" previous_ep # Per evitare di scaricare tutti gli episodi in una sola volta e riprendere da un certo punto

for (( i=0; i<$previous_ep; i++ ))
do
    sed -i '1d' $link_file # Cancella le righe "gia' scaricate"
done



j=0
for Line in $(cat $link_file)
do
    j=$((j+1))  # Conta gli episodi rimanenti
done
echo "Ci sono $j episodi rimanenti"


i=$((previous_ep+1))

for Line in $(cat $link_file)
do
    echo "Opening with chromium: $Line"

    chromium --headless --disable-gpu --dump-dom $Line > $website2_file 2>&1
    
    grep -Po "https:\/\/streamz.vg\/getlink-\w+\.dll" $website2_file > $website3_file # Regex per trovare il link di download (anche JS!)
    
    # QUESTO WHILE DOVREBBE PERMETTE DI RISOLVERE MANUALMENTE I CAPTCHA MA FA SCHIFO, SI ATTENDONO NUOVE SOLUZIONI
    var=$(cat $website3_file)

    while [ -z $var ]
    do
       echo "Please resolve captcha"
						# SOLUZIONE MANUALE
       read -p "Press enter to continue"

       chromium --headless --disable-gpu --dump-dom $Line > $website2_file 2>&1
       grep -Po "https:\/\/streamz.vg\/getlink-\w+\.dll" $website2_file > $website3_file
       var=$(cat $website3_file)
    done

    wget $(cat $website3_file) --output-document="EP${i}.mp4" # Scarica il file
    i=$((i+1)) # Incrementa numero episodio

    rm $website2_file
    rm $website3_file
    
done
